$background = rgb(2E2F29)
$foreground = rgb(DBD9CF)
$color0 = rgb(53544D)
$color1 = rgb(252A10)
$color2 = rgb(4B4A2D)
$color3 = rgb(4E4D2F)
$color4 = rgb(4E4E37)
$color5 = rgb(736D58)
$color6 = rgb(736D59)
$color7 = rgb(C4C0B2)
$color8 = rgb(89867D)
$color9 = rgb(313815)
$color10 = rgb(64633C)
$color11 = rgb(68663F)
$color12 = rgb(686749)
$color13 = rgb(999176)
$color14 = rgb(999176)
$color15 = rgb(C4C0B2)
