# Sourcing external config files

# Default Configs
$configs = $HOME/.config/hypr/configs

source=$configs/Settings.conf
source=$configs/Keybinds.conf

# User Config files
$UserConfigs = $HOME/.config/hypr/UserConfigs/
source=$UserConfigs/ENVariables.conf
source=$UserConfigs/Startup_Apps.conf
source=$UserConfigs/Monitors.conf
source=$configs/Animations.conf
source=$configs/WindowRules.conf

# User Configs
#$UserConfigs = $HOME/.config/hypr/UserConfigs

#source= $UserConfigs/Startup_Apps.conf
#source= $UserConfigs/ENVariables.conf
#source= $UserConfigs/Monitors.conf
#source= $UserConfigs/Laptops.conf
#source= $UserConfigs/LaptopDisplay.conf
#source= $UserConfigs/WindowRules.conf
#source= $UserConfigs/UserDecorAnimations.conf
#source= $UserConfigs/UserKeybinds.conf
#source= $UserConfigs/UserSettings.conf
#source= $UserConfigs/WorkspaceRules.conf
