# Monitors
#monitor = ,preferred,auto,auto
monitor = DP-2, highrr, 0x800, auto
monitor = DP-1, preferred, auto, auto, transform, 3
# NOTE: for laptop, kindly check notes in Laptops.conf regarding display
# Created this inorder for the monitor display to not wake up if not intended.
# See here: https://github.com/hyprwm/Hyprland/issues/4090

